// Generated by CoffeeScript 1.12.7
(function() {
  var fill;

  fill = (function(_this) {
    return function(container, liquid) {
      if (liquid == null) {
        liquid = "coffee";
      }
      return "Filling the " + container + " with " + liquid + ".";
    };
  })(this);

  module.exports = fill;

}).call(this);
